//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Bod { get; set; }
        public string District { get; set; }
        public string Telephone_No { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public string Entered_User { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public string Modify_User { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
