//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PId { get; set; }
        public string pcode { get; set; }
        public string barcode { get; set; }
        public string pdesc { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> reorder { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Province { get; set; }
        public string Product_Type { get; set; }
        public string Img_Path { get; set; }
    }
}
