//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DETAILS
    {
        public int PD_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string DESCR { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
