//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockIn
    {
        public int id { get; set; }
        public string refno { get; set; }
        public string pcode { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public string stockinby { get; set; }
        public string status { get; set; }
        public string vendor { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> OurPrice { get; set; }
        public Nullable<double> LoyalityPrice { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> GrossTotal { get; set; }
        public Nullable<double> Discounts { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string TelephoneNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<bool> IsFullPayed { get; set; }
        public Nullable<double> FreeQty { get; set; }
    }
}
